// telegram-settings/src/App.tsx
import React from 'react';
import './App.css';
import {Views} from "./statics/Views";
import MainMenu from "./views/MainMenu";
import SettingsMenu from "./views/SettingsMenu";
import QuestionMainMenu from "./views/QuestionMainMenu";
import ChatMenu from "./views/ChatMenu";
import LogsMenu from "./views/LogMenu";
import Loading from "./views/Loading";
import DebugMenu from "./views/DebugMenu";
import TopicsMenu from "./views/TopicsMenu";
import AboutMenu from "./views/AboutMenu";
import ChatGTPMenu from "./views/ChatGTPMenu";


interface Props {

}

interface State {
    currentView: Views;
}

class App extends React.Component<Props, State> {
    homeyAvailable: boolean = false;

    constructor(props: Props) {
        super(props);
        this.state = {
            currentView: Views.Loading,
        }
    }

    componentDidMount() {
        const interval = setInterval(() => {
            if (window.Homey && window.HomeyReady || process.env!.NODE_ENV === "development") {
                this.homeyAvailable = true;
                this.handleHomey();
                clearInterval(interval)
            }
        }, 100)
    }

    handleHomey() {
        if (!this.homeyAvailable) return;
        this.setState({
            currentView: Views.MainMenu,
        })
    }

    changeView(view: Views) {
        this.setState({
            currentView: view,
        })
    }

    render() {
        switch (this.state.currentView) {
            case Views.Topics:
                return <TopicsMenu changeView={this.changeView.bind(this)}/>;
            case Views.Debug:
                return <DebugMenu changeView={this.changeView.bind(this)}/>;
            case Views.Settings:
                return <SettingsMenu changeView={this.changeView.bind(this)}/>
            case Views.Questions:
                return <QuestionMainMenu changeView={this.changeView.bind(this)}/>;
            case Views.Users:
                return <ChatMenu changeView={this.changeView.bind(this)}/>;
            case Views.Logs:
                return <LogsMenu changeView={this.changeView.bind(this)}/>;
            case Views.MainMenu:
                return <MainMenu changeView={this.changeView.bind(this)}/>
            case Views.Loading:
                return <Loading fullscreen={true}/>
            case Views.About:
                return <AboutMenu changeView={this.changeView.bind(this)}/>
            case Views.ChatGTP:
                return <ChatGTPMenu changeView={this.changeView.bind(this)}/>;
            default:
                return <MainMenu changeView={this.changeView.bind(this)}/>
        }
    }
}

export default App;

// telegram-settings-vue/src/App.vue
<script setup lang="ts">
import {onMounted, ref} from "vue";
import MainMenu from "./views/MainMenu.vue";
import SettingsMenu from "./views/SettingsMenu.vue";
import Loading from "./views/Loading.vue";
import QuestionMainMenu from "./views/QuestionMainMenu.vue";
import ChatMenu from "./views/ChatMenu.vue";
import TopicsMenu from "./views/TopicsMenu.vue";
import LogMenu from "./views/LogMenu.vue";
import DebugMenu from "./views/DebugMenu.vue";
import AboutMenu from "./views/AboutMenu.vue";
import {Views} from "./statics/views";
import "./App.css";

const currentView = ref(Views.Loading);
const homeyAvailable = ref(false);

function changeView(view: Views) {
  currentView.value = view;
}

function handleHomey() {
  if (!homeyAvailable.value) {
    return;
  }
  currentView.value = Views.MainMenu;
}

onMounted(() => {
  const interval = window.setInterval(() => {
    if ((window.Homey && window.HomeyReady) || import.meta.env.DEV) {
      homeyAvailable.value = true;
      handleHomey();
      window.clearInterval(interval);
    }
  }, 100);
});
</script>

<template>
  <SettingsMenu
    v-if="currentView === Views.Settings"
    :change-view="changeView"
  />
  <QuestionMainMenu
    v-else-if="currentView === Views.Questions"
    :change-view="changeView"
  />
  <ChatMenu
    v-else-if="currentView === Views.Users"
    :change-view="changeView"
  />
  <TopicsMenu
    v-else-if="currentView === Views.Topics"
    :change-view="changeView"
  />
  <LogMenu
    v-else-if="currentView === Views.Logs"
    :change-view="changeView"
  />
  <DebugMenu
    v-else-if="currentView === Views.Debug"
    :change-view="changeView"
  />
  <AboutMenu
    v-else-if="currentView === Views.About"
    :change-view="changeView"
  />
  <MainMenu
    v-else-if="currentView === Views.MainMenu"
    :change-view="changeView"
  />
  <Loading
    v-else
    :fullscreen="true"
  />
</template>
