// telegram-settings/src/views/QuestionOverview.tsx
import React from 'react';
import '../App.css';
import {Views} from "../statics/Views";
import MenuItemGroup from "../components/UIComps/MenuItemGroup";
import MenuItemWrapper from "../components/UIComps/MenuItemWrapper";
import Badge from "../components/UIComps/Badge";
import {BadgeColor, BadgeSize, BadgeType} from "../statics/Colors";
import {Question} from "../statics/Question";
import Loading from "./Loading";
import Homey from "../Homey";
import EmptyWidget from "../components/UIComps/EmptyWidget";

interface Props {
    changeView: Function
}

interface State {
    questions: Question[]
    gotData: boolean
}

export default class QuestionOverview extends React.Component<Props, State> {
    constructor(props: Props) {
        super(props);
        this.state = {
            questions: [],
            gotData: process.env!.NODE_ENV === "development"
        }
    }

    async componentDidMount() {
        this.setState({
            questions: JSON.parse(await Homey.get("questions") ?? "[]"),
            gotData: true,
        })
    }

    getQuestionsComponents() {
        let result: any[] = [];
        this.state.questions.forEach((q) => {
            result.push(
                <MenuItemGroup>
                    <MenuItemWrapper onClick={() => this.props.changeView(Views.Questions_Edit, q)}>
                        <span style={{paddingBottom: "var(--su)", paddingTop: "var(--su)"}}>
                            {q.question}&nbsp;
                            <Badge color={BadgeColor.GRAY}
                                   type={BadgeType.PILL}
                                   size={BadgeSize.SMALL}>
                            <i className="fas fa-fingerprint"></i> {q.UUID}
                            </Badge>&nbsp;
                            <Badge color={BadgeColor.GRAY}
                                   type={BadgeType.PILL}
                                   size={BadgeSize.SMALL}>
                                <i className="fas fa-keyboard"></i> {q.buttons.length}
                            </Badge>
                        </span>
                        <span
                            className={"editButton hy-nostyle"}>
                            {Homey.__("settings.misc.edit")} <i className="fa fa-chevron-right"></i>
                        </span>
                    </MenuItemWrapper>
                </MenuItemGroup>
            )
        });
        return result;
    }

    render() {
        if (!this.state.gotData) return <Loading fullscreen={true}/>
        if (this.state.questions.length === 0) return <EmptyWidget/>
        else return (<>{this.getQuestionsComponents()}</>);
    }
}

// telegram-settings-vue/src/views/QuestionOverview.vue
<script setup lang="ts">
import {onMounted, ref} from "vue";
import "../App.css";
import Homey from "../Homey";
import {Views} from "../statics/views";
import type {QuestionModel} from "../types/models";
import {BadgeColor, BadgeSize, BadgeType} from "../statics/colors";
import {getJsonSetting} from "../utils/settings";
import Loading from "./Loading.vue";
import MenuItemGroup from "../components/UIComps/MenuItemGroup.vue";
import MenuItemWrapper from "../components/UIComps/MenuItemWrapper.vue";
import Badge from "../components/UIComps/Badge.vue";
import EmptyWidget from "../components/UIComps/EmptyWidget.vue";

const props = defineProps<{
  changeView: (view?: Views, targetQuestion?: QuestionModel) => void
}>();

const questions = ref<QuestionModel[]>([]);
const gotData = ref(import.meta.env.DEV);

onMounted(async () => {
  questions.value = await getJsonSetting<QuestionModel[]>("questions", []);
  gotData.value = true;
});
</script>

<template>
  <Loading
    v-if="!gotData"
    :fullscreen="true"
  />
  <EmptyWidget
    v-else-if="questions.length === 0"
  />
  <template v-else>
    <MenuItemGroup
      v-for="question in questions"
      :key="question.UUID"
    >
      <MenuItemWrapper @click="props.changeView(Views.QuestionsEdit, question)">
        <span style="padding-bottom: var(--su); padding-top: var(--su);">
          {{ question.question }}&nbsp;
          <Badge
            :color="BadgeColor.GRAY"
            :type="BadgeType.PILL"
            :size="BadgeSize.SMALL"
          >
            <i class="fas fa-fingerprint"></i> {{ question.UUID }}
          </Badge>&nbsp;
          <Badge
            :color="BadgeColor.GRAY"
            :type="BadgeType.PILL"
            :size="BadgeSize.SMALL"
          >
            <i class="fas fa-keyboard"></i> {{ question.buttons.length }}
          </Badge>
        </span>
        <span class="editButton hy-nostyle">
          {{ Homey.__("settings.misc.edit") }} <i class="fa fa-chevron-right"></i>
        </span>
      </MenuItemWrapper>
    </MenuItemGroup>
  </template>
</template>
