// telegram-settings-vue/src/components/UIComps/EmptyWidget.vue
<script setup lang="ts">
import "../../App.css";
import "./EmptyWidget.css";
import Homey from "../../Homey";

defineProps<{
  happy?: boolean
}>();
</script>

<template>
  <div class="emptyWidget">
    {{ Homey.__("settings.misc.empty") }}!
    <i
      v-if="happy"
      class="fas fa-smile-beam"
    ></i>
    <i
      v-else
      class="fas fa-sad-tear"
    ></i>
  </div>
</template>

// telegram-settings/src/components/UIComps/EmptyWidget.tsx
import React from 'react';
import '../../App.css';
import emptyStyle from './EmptyWidget.module.css'
import Homey from "../../Homey";

interface Props {
    happy?: boolean;
}

interface State {
}


export default class EmptyWidget extends React.Component<Props, State> {

    constructor(props: Props) {
        super(props);
    }

    render() {
        return (
            <div className={emptyStyle.widget}>
                {Homey.__('settings.misc.empty')}! {this.props.happy ? <i className="fas fa-smile-beam"></i> :
                <i className="fas fa-sad-tear"></i>}
            </div>
        );
    }
}
