// telegram-settings-vue/src/views/MainMenu.vue
<script setup lang="ts">
import MenuItem from "../components/UIComps/MenuItem.vue";
import MenuItemGroup from "../components/UIComps/MenuItemGroup.vue";
import StatusWidget from "../components/MainMenu/StatusWidget.vue";
import Homey from "../Homey";
import {Views} from "../statics/views";

defineProps<{
  changeView: (view: Views) => void
}>();
</script>

<template>
  <div class="spacer"></div>
  <StatusWidget />
  <MenuItemGroup>
    <MenuItem
      :title="Homey.__('settings.mainMenu.settings')"
      icon="fa-cog"
      class-name="bg-color-orange"
      @click="changeView(Views.Settings)"
    />
    <MenuItem
      :title="Homey.__('settings.mainMenu.questions')"
      icon="fa-question"
      class-name="bg-color-blue"
      @click="changeView(Views.Questions)"
    />
    <MenuItem
      :title="Homey.__('settings.mainMenu.users')"
      icon="fa-users"
      class-name="bg-color-magenta"
      @click="changeView(Views.Users)"
    />
    <MenuItem
      :title="Homey.__('settings.mainMenu.topics')"
      icon="fa-folder"
      class-name="bg-color-green"
      @click="changeView(Views.Topics)"
    />
  </MenuItemGroup>
  <MenuItemGroup>
    <MenuItem
      :title="Homey.__('settings.mainMenu.logs')"
      icon="fa-bars"
      class-name="bg-color-gray"
      @click="changeView(Views.Logs)"
    />
    <MenuItem
      :title="Homey.__('settings.mainMenu.debugMenu')"
      icon="fa-bug"
      class-name="bg-color-red"
      @click="changeView(Views.Debug)"
    />
  </MenuItemGroup>
  <MenuItemGroup>
    <MenuItem
      :title="Homey.__('settings.aboutMenu.joinTelegram')"
      icon="fa-paper-plane"
      class-name="bg-color-blue"
      @click="Homey.popup('https://t.me/homeyCommunity')"
    />
    <MenuItem
      :title="Homey.__('settings.mainMenu.about')"
      icon="fa-address-card"
      class-name="bg-color-magenta"
      @click="changeView(Views.About)"
    />
  </MenuItemGroup>
</template>

// telegram-settings/src/views/MainMenu.tsx
import React from 'react';
import '../App.css';
import MenuItem from "../components/UIComps/MenuItem";
import {Views} from "../statics/Views";
import MenuItemGroup from "../components/UIComps/MenuItemGroup";
import StatusWidget from "../components/MainMenu/StatusWidget";
import Homey from "../Homey";

interface Props {
    changeView: Function
}

export default class MainMenu extends React.Component<Props> {
    render() {
        return (
            <>
                <div className={"spacer"}></div>
                <StatusWidget/>
                <MenuItemGroup>
                    <MenuItem
                        title={Homey.__('settings.mainMenu.settings')}
                        icon={"fa-cog"}
                        className={"bg-color-orange"}
                        onClick={() => this.props.changeView(Views.Settings)}
                    />
                    <MenuItem
                        title={Homey.__('settings.mainMenu.questions')}
                        icon={"fa-question"}
                        className={"bg-color-blue"}
                        onClick={() => this.props.changeView(Views.Questions)}
                    />
                    <MenuItem
                        title={Homey.__('settings.mainMenu.users')}
                        icon={"fa-users"}
                        className={"bg-color-magenta"}
                        onClick={() => this.props.changeView(Views.Users)}
                    />
                    <MenuItem
                        title={Homey.__('settings.mainMenu.topics')}
                        icon={"fa-folder"}
                        className={"bg-color-green"}
                        onClick={() => this.props.changeView(Views.Topics)}
                    />
                </MenuItemGroup>
                <MenuItemGroup>
                    <MenuItem
                        title={Homey.__('settings.mainMenu.logs')}
                        icon={"fa-bars"}
                        className={"bg-color-gray"}
                        onClick={() => this.props.changeView(Views.Logs)}
                    />
                    <MenuItem
                        title={Homey.__('settings.mainMenu.debugMenu')}
                        icon={"fa-bug"}
                        className={"bg-color-red"}
                        onClick={() => this.props.changeView(Views.Debug)}
                    />
                </MenuItemGroup>
                <MenuItemGroup>
                    <MenuItem
                        title={Homey.__('settings.aboutMenu.joinTelegram')}
                        icon={"fa-paper-plane"}
                        className={"bg-color-blue"}
                        onClick={() => Homey.popup("https://t.me/homeyCommunity")}
                    />
                    <MenuItem
                        title={Homey.__('settings.mainMenu.about')}
                        icon={"fa-address-card"}
                        className={"bg-color-magenta"}
                        onClick={() => this.props.changeView(Views.About)}
                    />
                </MenuItemGroup>
            </>
        );
    }
}
