// telegram-settings-vue/src/views/QuestionMainMenu.vue
<script setup lang="ts">
import {computed, ref} from "vue";
import "../App.css";
import Homey from "../Homey";
import {Views} from "../statics/views";
import type {QuestionModel} from "../types/models";
import MenuWrapper from "../components/UIComps/MenuWrapper.vue";
import QuestionMenu from "./QuestionMenu.vue";
import QuestionOverview from "./QuestionOverview.vue";

const props = defineProps<{
  changeView: (view: Views) => void
}>();

const currentView = ref(Views.QuestionsOverview);
const targetQuestion = ref<QuestionModel | undefined>(undefined);

function changeQuestionView(view?: Views, question?: QuestionModel) {
  if (view === undefined) {
    return;
  }

  if (view === Views.MainMenu) {
    props.changeView(Views.MainMenu);
    return;
  }

  currentView.value = view;
  targetQuestion.value = question;
}

const viewConfig = computed(() => {
  switch (currentView.value) {
    case Views.QuestionsOverview:
      return {
        title: Homey.__("settings.questionMenu.questions"),
        backView: Views.MainMenu,
        addView: Views.QuestionsAdd
      };
    case Views.QuestionsAdd:
      return {
        title: Homey.__("settings.questionMenu.addQuestion"),
        backView: Views.QuestionsOverview
      };
    case Views.QuestionsEdit:
      return {
        title: Homey.__("settings.questionMenu.editQuestion"),
        backView: Views.QuestionsOverview
      };
    default:
      props.changeView(Views.MainMenu);
      return {
        title: Homey.__("settings.questionMenu.questions"),
        backView: Views.MainMenu
      };
  }
});
</script>

<template>
  <MenuWrapper
    :title="viewConfig.title"
    :on-back="() => changeQuestionView(viewConfig.backView)"
    :on-add="viewConfig.addView !== undefined ? () => changeQuestionView(viewConfig.addView) : undefined"
  >
    <QuestionOverview
      v-if="currentView === Views.QuestionsOverview"
      :change-view="changeQuestionView"
    />
    <QuestionMenu
      v-else-if="currentView === Views.QuestionsAdd"
      :change-view-on-save="changeQuestionView"
    />
    <QuestionMenu
      v-else
      :change-view-on-save="changeQuestionView"
      :question="targetQuestion"
    />
  </MenuWrapper>
</template>

// telegram-settings/src/views/QuestionMainMenu.tsx
import React from 'react';
import '../App.css';
import MenuWrapper from "../components/UIComps/MenuWrapper";
import {Views} from "../statics/Views";
import {Question} from "../statics/Question";
import QuestionMenu from "./QuestionMenu";
import Homey from "../Homey";
import QuestionOverview from "./QuestionOverview";

interface Props {
    changeView: Function
}

interface State {
    currentView: Views
    targetQuestion?: Question
}

export default class QuestionMainMenu extends React.Component<Props, State> {
    constructor(props: Props) {
        super(props);
        this.state = {
            currentView: Views.Questions_Overview,
        }
    }
    changeView(view: Views | undefined, targetQuestion?: Question) {
        if (view === undefined) return;
        this.setState({
            currentView: view,
            targetQuestion: targetQuestion
        });
    }

    getView() {
        switch (this.state.currentView) {
            case Views.Questions_Overview:
                return {
                    comp: <QuestionOverview changeView={this.changeView.bind(this)}/>,
                    title: Homey.__("settings.questionMenu.questions"),
                    backView: Views.MainMenu,
                    addView: Views.Questions_Add
                };
            case Views.Questions_Add:
                return {
                    comp: <QuestionMenu changeViewOnSave={this.changeView.bind(this)}/>,
                    title: Homey.__("settings.questionMenu.addQuestion"),
                    backView: Views.Questions_Overview,
                    addView: undefined
                };
            case Views.Questions_Edit:
                return {
                    comp: <QuestionMenu changeViewOnSave={this.changeView.bind(this)}
                                        question={this.state.targetQuestion}/>,
                    title: Homey.__("settings.questionMenu.editQuestion"),
                    backView: Views.Questions_Overview,
                    addView: undefined
                };
            default:
                this.props.changeView(Views.MainMenu);
                return {
                    comp: <QuestionOverview changeView={this.changeView.bind(this)}/>,
                    title: Homey.__("settings.questionMenu.questions"),
                    backView: Views.MainMenu,
                    addView: undefined
                };
        }
    }

    render() {
        return (
            <MenuWrapper title={this.getView().title}
                         onBack={() => this.changeView(this.getView().backView)}
                         onAdd={this.getView().addView !== undefined ? () => this.changeView(this.getView().addView) : undefined}
            >
                {this.getView().comp}
            </MenuWrapper>
        );
    }
}
