// telegram-settings-vue/src/views/TopicsMenu.vue
<script setup lang="ts">
import {computed, onMounted, ref} from "vue";
import "../App.css";
import Homey from "../Homey";
import {Views} from "../statics/views";
import type {Chat} from "../types/models";
import {BadgeColor} from "../statics/colors";
import {getJsonSetting, setJsonSetting} from "../utils/settings";
import Loading from "./Loading.vue";
import MenuWrapper from "../components/UIComps/MenuWrapper.vue";
import MenuItemGroup from "../components/UIComps/MenuItemGroup.vue";
import MenuItemWrapper from "../components/UIComps/MenuItemWrapper.vue";
import Badge from "../components/UIComps/Badge.vue";
import EmptyWidget from "../components/UIComps/EmptyWidget.vue";

const props = defineProps<{
  changeView: (view: Views) => void
}>();

const chats = ref<Chat[]>([]);
const gotData = ref(import.meta.env.DEV);

const chatsWithTopics = computed(() => chats.value.filter((chat) => (chat.topics?.length ?? 0) > 0));

onMounted(async () => {
  chats.value = await getJsonSetting<Chat[]>("users", []);
  gotData.value = true;
});

async function deleteTopic(chatId: number, topicId: number) {
  gotData.value = false;

  chats.value = chats.value.map((chat) => {
    if (chat.chatId !== chatId) {
      return chat;
    }

    return {
      ...chat,
      topics: (chat.topics ?? []).filter((topic) => topic.topicId !== topicId)
    };
  });

  await setJsonSetting("users", chats.value);
  gotData.value = true;
}
</script>

<template>
  <Loading
    v-if="!gotData"
    :fullscreen="true"
  />
  <MenuWrapper
    v-else
    :title="Homey.__('settings.topicsMenu.topicsMenu')"
    :on-back="() => props.changeView(Views.MainMenu)"
  >
    <EmptyWidget v-if="chatsWithTopics.length === 0" />
    <MenuItemGroup
      v-for="chat in chatsWithTopics"
      :key="chat.chatId"
    >
      <p class="itemGroupTitle">
        {{ chat.chatName }}
      </p>
      <MenuItemWrapper
        v-for="topic in chat.topics"
        :key="`${chat.chatId}-${topic.topicId}`"
      >
        <span>
          {{ topic.topicName }}&nbsp;
          <Badge :color="BadgeColor.GRAY">
            <i class="fas fa-fingerprint"></i> {{ topic.topicId }}
          </Badge>
        </span>
        <button
          class="removeButton hy-nostyle"
          @click="deleteTopic(chat.chatId, topic.topicId)"
        >
          <i class="fas fa-trash-alt"></i>
        </button>
      </MenuItemWrapper>
    </MenuItemGroup>
  </MenuWrapper>
</template>

// telegram-settings/src/views/TopicsMenu.tsx
import React from 'react';
import '../App.css';
import MenuWrapper from "../components/UIComps/MenuWrapper";
import {Views} from "../statics/Views";
import MenuItemWrapper from "../components/UIComps/MenuItemWrapper";
import MenuItemGroup from "../components/UIComps/MenuItemGroup";
import Badge from "../components/UIComps/Badge";
import {BadgeColor} from "../statics/Colors";
import {Chat} from "../statics/Chat";
import Loading from "./Loading";
import Homey from "../Homey";

interface Props {
    changeView: Function
}

interface State {
    chats: Chat[]
    gotData: boolean
}

export default class TopicsMenu extends React.Component<Props, State> {
    constructor(props: Props) {
        super(props);
        this.state = {
            chats: [],
            gotData: process.env!.NODE_ENV === "development"
        }
    }

    async componentDidMount() {
        this.setState({
            chats: JSON.parse(await Homey.get("users") ?? "[]"),
            gotData: true,
        })
    }

    getChatComponents() {
        let result: any[] = [];
        this.state.chats.forEach((u) => {
            if (u.topics && u.topics.length > 0)
                result.push(
                    <MenuItemGroup>
                        <p className="itemGroupTitle">
                            {u.chatName}
                        </p>
                        {u.topics.map((t) => {
                            return (
                                <MenuItemWrapper>
                                    <span>{t.topicName}&nbsp;
                                        <Badge color={BadgeColor.GRAY}>
                                            <i className="fas fa-fingerprint"></i> {t.topicId}
                                        </Badge>
                                    </span>
                                    <button className="removeButton hy-nostyle"
                                            onClick={() => this.deleteTopic(u.chatId, t.topicId)}><i
                                        className="fas fa-trash-alt"></i></button>
                                </MenuItemWrapper>
                            );
                        })}
                    </MenuItemGroup>
                )
        });
        return result;
    }

    render() {
        if (!this.state.gotData) return <Loading fullscreen={true}/>
        else return (
            <MenuWrapper title={Homey.__("settings.topicsMenu.topicsMenu")}
                         onBack={() => this.props.changeView(Views.MainMenu)}>
                {this.getChatComponents()}
            </MenuWrapper>
        );
    }

    private deleteTopic(chatId: number, topicId: number) {
        let chats = this.state.chats;
        let chat = this.state.chats.find((u: Chat) => u.chatId === chatId);
        if (!chat || !chat.topics) return;
        chat.topics = chat.topics.filter((t) => t.topicId !== topicId);
        chats = this.state.chats.filter((u: Chat) => u.chatId !== chatId);
        chats.push(chat);
        this.setState({
            gotData: false,
            chats: chats
        });
        Homey.set('users', JSON.stringify(chats))?.then(() =>
            this.setState({
                gotData: true,
            })
        );
    }
}
