// telegram-settings-vue/src/components/MainMenu/StatusWidget.vue
<script setup lang="ts">
import {computed, onMounted, reactive} from "vue";
import "../../App.css";
import "./StatusWidget.css";
import Loading from "../../views/Loading.vue";
import Homey from "../../Homey";
import iconUrl from "../../assets/icon.svg";

type LogEntry = {
  type: number
};

const state = reactive({
  running: undefined as boolean | undefined,
  users: "0",
  questions: "0",
  logSize: "0",
  errors: "0",
  privacyCommand: false,
  gotData: import.meta.env.DEV
});

const statusLabel = computed(() => {
  if (import.meta.env.DEV) {
    return "DEVELOPMENT";
  }
  if (state.running === undefined) {
    return Homey.__("settings.status.state.unknown");
  }
  return state.running
    ? Homey.__("settings.status.state.on")
    : Homey.__("settings.status.state.off");
});

const statusClass = computed(() => {
  if (import.meta.env.DEV) {
    return "badge orange";
  }
  if (state.running === undefined) {
    return "badge gray";
  }
  return state.running ? "badge green" : "badge red";
});

onMounted(async () => {
  const logs = JSON.parse((await Homey.get<string>("logs")) ?? "[]") as LogEntry[];
  state.running = await Homey.get<boolean>("bot-running");
  state.users = String((JSON.parse((await Homey.get<string>("users")) ?? "[]") as unknown[]).length ?? 0);
  state.questions = String((JSON.parse((await Homey.get<string>("questions")) ?? "[]") as unknown[]).length ?? 0);
  state.logSize = String(logs.length ?? 0);
  state.errors = String(logs.filter((entry) => entry.type === 1).length ?? 0);
  state.privacyCommand = (await Homey.get<boolean>("privacyCommand")) ?? false;
  state.gotData = true;
});
</script>

<template>
  <div
    v-if="state.gotData"
  >
    <div class="statusWidget">
      <div class="title">
        Status
      </div>
      <hr />
      <div class="data">
        <div class="data">
          <div class="col">
            <p>{{ Homey.__("settings.status.bot") }}: <span :class="statusClass">{{ statusLabel }}</span></p>
            <p>{{ Homey.__("settings.status.chats") }}: {{ state.users }}</p>
            <p>{{ Homey.__("settings.status.questions") }}: {{ state.questions }}</p>
          </div>
          <div class="col">
            <p>{{ Homey.__("settings.status.logSize", {value: state.logSize}) }}</p>
            <p>{{ Homey.__("settings.status.errors") }}: {{ state.errors }}</p>
            <p></p>
          </div>
        </div>
        <img
          :src="iconUrl"
          height="60"
          width="60"
          class="logo telegramColorFilter"
          alt="Telegram Logo"
        />
      </div>
    </div>
    <div
      v-if="!state.privacyCommand"
      class="warningWidget"
    >
      <i class="fas fa-exclamation-triangle"></i> {{ Homey.__('settings.botSettings.privacyCommandWarning') }}
    </div>
  </div>
  <div
    v-else
    class="statusWidget"
  >
    <Loading />
  </div>
</template>

// telegram-settings/src/components/MainMenu/StatusWidget.tsx
import React, {ReactElement} from 'react';
import '../../App.css';
import './StatusWidget.css'
import Loading from "../../views/Loading";
import Badge from "../UIComps/Badge";
import {BadgeColor, BadgeSize} from "../../statics/Colors";
import {LogEntry} from "../../statics/LogEntry";
import Homey from "../../Homey";

interface Props {

}

interface State {
    status: ReactElement;
    users: string;
    questions: string;
    logSize: string;
    errors: string;
    privacyCommand: boolean;
    gotData: boolean;
}

export default class StatusWidget extends React.Component<Props, State> {

    constructor(props: Props) {
        super(props);
        this.state = {
            status: this.getStatusBadge(undefined),
            users: "0",
            questions: "0",
            logSize: "0",
            errors: "0",
            privacyCommand: false,
            gotData: process.env!.NODE_ENV === "development"
        }
    }

    getStatusBadge(bool: boolean | undefined) {
        if (process.env!.NODE_ENV === "development")
            return <Badge color={BadgeColor.ORANGE}
                          size={BadgeSize.SMALL}>DEVELOPMENT</Badge>;
        if (bool === undefined)
            return <Badge color={BadgeColor.GRAY}
                          size={BadgeSize.SMALL}>{Homey.__("settings.status.state.unknown")}</Badge>;
        if (bool)
            return <Badge color={BadgeColor.GREEN}
                          size={BadgeSize.SMALL}>{Homey.__("settings.status.state.on")}</Badge>;
        return <Badge color={BadgeColor.RED}
                      size={BadgeSize.SMALL}>{Homey.__("settings.status.state.off")}</Badge>;
    }

    async componentDidMount() {
        let logs = JSON.parse(await Homey.get('logs') ?? "[]") ?? [];
        this.setState({
            status: this.getStatusBadge(await Homey.get('bot-running')),
            users: (JSON.parse(await Homey.get('users') ?? "[]")).length ?? "0",
            questions: (JSON.parse(await Homey.get('questions') ?? "[]")).length ?? "0",
            logSize: logs.length ?? "0",
            errors: logs.filter((e: LogEntry) => e.type === 1).length ?? "0",
            privacyCommand: await Homey.get('privacyCommand') ?? false,
            gotData: true
        })
    }

    render() {
        if (this.state.gotData)
            return (
                <>
                    <div className="statusWidget">
                        <div className="title">
                            Status
                        </div>
                        <hr/>
                        <div className="data">
                            <div className={"data"}>
                                <div className="col">
                                    <p>{Homey.__("settings.status.bot")}: {this.state.status}</p>
                                    <p>{Homey.__("settings.status.chats")}: {this.state.users}</p>
                                    <p>{Homey.__("settings.status.questions")}: {this.state.questions}</p>
                                </div>
                                <div className="col">
                                    <p>{Homey.__("settings.status.logSize", {value: this.state.logSize})}</p>
                                    <p>{Homey.__("settings.status.errors")}: {this.state.errors}</p>
                                    <p></p>
                                </div>
                            </div>
                            <img src={"./img/icon.svg"} height={60} width={60} className={"logo telegramColorFilter"}
                                 alt={"Telegram Logo"}/>
                        </div>
                    </div>
                    {!this.state.privacyCommand ? <div className="warningWidget">
                            <i className={"fas fa-exclamation-triangle"}></i> {Homey.__('settings.botSettings.privacyCommandWarning')}
                        </div>
                        : ''}
                </>
            );
        else return <div className="statusWidget"><Loading/></div>
    }
}
