// telegram-settings/src/components/UIComps/MenuItem.tsx
import React, {MouseEventHandler} from 'react';
import '../../App.css';
import './MenuItem.css'
import Badge from "./Badge";
import {BadgeColor, BadgeSize, BadgeType} from "../../statics/Colors";

interface Props {
    title: string;
    icon: string;
    onClick?: MouseEventHandler<HTMLButtonElement>;
    disabled?: boolean;
    className: string;
}

export default class MenuItem extends React.Component<Props, any> {
    onClick(e: React.MouseEvent<HTMLButtonElement, MouseEvent>) {
        if (this.props.onClick) this.props.onClick(e)
    }

    render() {
        return (
            <button className={"menuItem hy-nostyle" + (this.props.disabled ? " disabled" : "")}
                    onClick={(e) => this.onClick(e)}>
                <span className={"iconSpan " + this.props.className}>
                    <i className={"menuIcon fas " + this.props.icon}></i>
                </span>
                {this.props.title}
                {!this.props.disabled && <i className="fa fa-chevron-right"></i>}
                {this.props.disabled && <Badge
                  style={{marginLeft: "1em"}}
                  type={BadgeType.PILL}
                  color={BadgeColor.GRAY}
                  size={BadgeSize.SMALL}>Coming soon</Badge>}
            </button>
        );
    }
}

// telegram-settings-vue/src/components/UIComps/MenuItem.vue
<script setup lang="ts">
import "../../App.css";
import "./MenuItem.css";

defineProps<{
  title: string
  icon: string
  className?: string
  disabled?: boolean
}>();

defineEmits<{
  click: []
}>();
</script>

<template>
  <button
    :class="`menuItem hy-nostyle${disabled ? ' disabled' : ''}`"
    :disabled="disabled"
    @click="$emit('click')"
  >
    <span :class="`iconSpan ${className ?? ''}`">
      <i :class="`menuIcon fas ${icon}`"></i>
    </span>
    {{ title }}
    <span
      v-if="disabled"
      class="menuItemSoon"
    >
      Soon
    </span>
    <i
      v-else
      class="fa fa-chevron-right"
    ></i>
  </button>
</template>
