// telegram-settings/src/components/UIComps/Switch.tsx
import React, {ChangeEventHandler} from 'react';
import '../../App.css';
import './Switch.css'

interface Props {
    id?: string;
    onChange: ChangeEventHandler<HTMLInputElement>;
    value?: boolean
    right?: boolean;
}

export default class Switch extends React.Component<Props, any> {
    render() {
        return (
            <label className={"switch " + (this.props.right || this.props.right == undefined ? "right" : "")}>
                <input
                    className="hy-nostyle"
                    id={this.props.id}
                    type="checkbox"
                    defaultChecked={this.props.value}
                    onChange={this.props.onChange}/>
                <span className="slider round"></span>
            </label>
        );
    }
}

// telegram-settings-vue/src/components/UIComps/Switch.vue
<script setup lang="ts">
import "../../App.css";
import "./Switch.css";

defineProps<{
  id?: string
  modelValue?: boolean
  right?: boolean
}>();

const emit = defineEmits<{
  "update:modelValue": [boolean]
}>();
</script>

<template>
  <label :class="`switch ${right === false ? '' : 'right'}`">
    <input
      :id="id"
      class="hy-nostyle"
      type="checkbox"
      :checked="modelValue"
      @change="emit('update:modelValue', ($event.target as HTMLInputElement).checked)"
    />
    <span class="slider round"></span>
  </label>
</template>
